// app/login/page.tsx
'use client';

import { useState, Suspense } from 'react';
import Link from 'next/link';
import { signIn } from 'next-auth/react';
import { useSearchParams } from 'next/navigation';

function LoginForm() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const searchParams = useSearchParams();
  const callbackUrl = searchParams.get('callbackUrl') || '/dashboard';

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError('');
    setLoading(true);
    const res = await signIn('credentials', { email, password, callbackUrl, redirect: false });
    setLoading(false);
    if (res?.error) {
      setError('Invalid email or password');
      return;
    }
    if (res?.ok) window.location.href = callbackUrl;
  }

  return (
    <div className="mx-auto max-w-sm px-4 py-16">
      <h1 className="section-heading">Sign in</h1>
      <form onSubmit={handleSubmit} className="mt-6 space-y-4">
        <div>
          <label htmlFor="email" className="block text-sm font-medium text-gray-700">
            Email
          </label>
          <input
            id="email"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 shadow-sm focus:border-[var(--color-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]"
          />
        </div>
        <div>
          <label htmlFor="password" className="block text-sm font-medium text-gray-700">
            Password
          </label>
          <input
            id="password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 shadow-sm focus:border-[var(--color-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]"
          />
        </div>
        {error && <p className="text-sm text-red-600">{error}</p>}
        <button type="submit" disabled={loading} className="btn-primary w-full">
          {loading ? 'Signing in…' : 'Sign in'}
        </button>
      </form>
      <p className="mt-4 text-center text-sm text-gray-600">
        Don&apos;t have an account?{' '}
        <Link href="/register" className="font-medium text-[var(--color-accent)] hover:underline">
          Register
        </Link>
      </p>
    </div>
  );
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="mx-auto max-w-sm px-4 py-16">Loading…</div>}>
      <LoginForm />
    </Suspense>
  );
}

// resources/js/Pages/Auth/Login.vue
<script setup>
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import PublicLayout from '@/Layouts/PublicLayout.vue';

const form = useForm({ email: '', password: '', remember: false });
const status = usePage().props.flash?.status;

function submit() {
  form.post('/login');
}
</script>

<template>
  <Head title="Login" />
  <PublicLayout>
    <div class="mx-auto max-w-md px-4 py-16">
      <h1 class="section-heading">Sign in</h1>
      <p v-if="status" class="mt-4 text-sm text-green-600">{{ status }}</p>
      <form class="mt-8 space-y-4" @submit.prevent="submit">
        <div>
          <label class="block text-sm font-medium">Email</label>
          <input v-model="form.email" type="email" required class="mt-1 w-full rounded-lg border px-3 py-2" />
          <p v-if="form.errors.email" class="mt-1 text-sm text-red-600">{{ form.errors.email }}</p>
        </div>
        <div>
          <label class="block text-sm font-medium">Password</label>
          <input v-model="form.password" type="password" required class="mt-1 w-full rounded-lg border px-3 py-2" />
        </div>
        <label class="flex items-center gap-2 text-sm">
          <input v-model="form.remember" type="checkbox" /> Remember me
        </label>
        <button type="submit" class="btn-primary w-full" :disabled="form.processing">Sign in</button>
      </form>
      <p class="mt-4 text-center text-sm">
        No account? <Link href="/register" class="text-[var(--color-accent)]">Register</Link>
      </p>
    </div>
  </PublicLayout>
</template>
